---
title: "DSO545 Midterm"
author: "Xu Zhang"
date: "March 6, 2018"
output: word_document
---

```{r }
setwd("C:/Users/Xu Zhang/Desktop")
library(dplyr)
library(lubridate)
library(ggplot2)
```

case1
```{r,echo=TRUE}
#Q1
case1=read.csv("tweets.csv")
case1$time=ymd_hms(case1$time)
case1 %>%
  filter(handle=="HillaryClinton") %>%
  mutate(Wday=wday(time,label=TRUE,abbr=FALSE)) %>%
  group_by(Wday) %>%
  summarise(count=n()) %>%
  ggplot(aes(x=Wday,y=count))+
  geom_col()+
  labs(title="Number of Tweets per day",x="",y="count")
```




```{r, echo=TRUE}
#Q2
Q2=case1 %>%
  filter(handle=="HillaryClinton") %>%
  mutate(Wday=wday(time,label=TRUE,abbr=FALSE),Hour=hour(time)) %>%
  group_by(Wday,Hour) %>%
  summarise(count=n())
  
ggplot(Q2,aes(x=Wday,y=Hour,fill=count))+
  geom_tile()+
  scale_fill_gradient(low = "white",
                      high = "darkred") +
  scale_y_continuous(breaks = seq(0,23,1))+
  labs(title="Heatmap of Hilary Clinton's Tweets",x="Day of week",y="Hour of day")
```

case2
```{r}
case2=read.csv("trump_approval_polls.csv")

#Q1
case2 %>%
  filter(ï..year==2018,month=="Feb") %>%
  arrange(approval) %>%
  slice(1) %>%
  select(pollster,approval)
```

```{r, echo=TRUE}
#Q2
 case2 %>%
   filter(!is.na(grade)) %>%
   filter(ï..year==2018) %>%
   group_by(grade) %>%
   ggplot(aes(x=approval,fill=grade)) +
   geom_density(col=NA,alpha=0.5)+
   geom_line(stat = "density")+
   scale_x_continuous(limits = c(30,60),labels = c("30%","40%","50%","60%"))+
   labs(title="Trumps's Approval Rating in 2018 by Pollster Grade",x="Approval Rating",y="density")
```

case3
```{r}
 case3=read.csv("top250_beers.csv")

 #Q1
 case3 %>%
   group_by(brewery) %>%
   summarise(count=n(),
             avg_rating=mean(rating)) %>%
   arrange(-count) %>%
   slice(1)
```

```{r, echo=TRUE}
#Q2
 case3 %>%
   group_by(style) %>%
   summarise(TNum_of_rating=sum(num_ratings)/1000) %>%
   ggplot(aes(x=reorder(style,TNum_of_rating) ,y=TNum_of_rating))+
   geom_col(fill="red")+
   coord_flip()+
   scale_y_continuous(breaks = seq(0,125,25),labels = c("0K","25K","50K","75K","100K","125K"))+
   labs(title="Total Number of Rating by Style",x="Style",y="Number og Ratings")
```


